Fix PowerTools repository name for CentOS 8.3
This fixes below error when enabling PowerTools repo:

 $ sudo yum config-manager --set-enabled PowerTools
 Error: No matching repo to modify: PowerTools.

Because of it DevStack fails later becaouse not
being able to install libyaml-devel

By replacing above command with below one the error
disappears

 $ sudo yum config-manager --set-enabled powertools

After it we are later able to install libyaml-devel
package

Change-Id: I92088f426ff3f5398978de61fdf53e120e403091