Update patch set 41
Patch Set 41: Code-Review-1

I'm still having trouble getting this to work.  On a clean fedora 20 vm, I'm seeing ffi fail to install because libffi-devel dependency isn't found (this may be unrelated).  When I install the package manually, stack.sh reports successful exit status, but no openstack processes are running.  Running stack.sh again fails with a librados authentication error.  Running unstack.sh shows an error that vish isn't installed.  When I install 'libvirt-client' by hand, I then see

error: failed to connect to the hypervisor
error: no valid connection
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory

Hopefully this helps a bit, let me know if you need any additional info.

Patch-set: 41