Update patch set 1
Patch Set 1:

also jenkins is failing because of this: 

RuntimeError: Config file /opt/stack/new/tempest/etc/tempest.conf not found

Doesn't seeem to be due to the change I made here.

Patch-set: 1