Glance: Add RBD to known_stores when Ceph is enabled
If the Ceph service is enabled, ensure the RBD store
is added to the list of known_stores for Glance.

If missing, you will see an error like:
 ERROR: Store for scheme rbd not found

Change-Id: I93033b55ef0ac3356a18cd38a34fd92da407c3f7