Update patch set 2
Patch Set 2:

This is failing because n-cpu won't start, because we get this error trying to start libvirtd:

libvirtError: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied

libvirtd is running.

I see this in the libvirtd logs:

2018-01-05 16:50:52.125+0000: 11136: error : virSecurityDriverLookup:80 : unsupported configuration: Security driver apparmor not enabled

So it seems that not using Pike UCA has caused some other fallout...

Patch-set: 2
Label: Verified=0