Update patch set 1
Patch Set 1:

For ex cinder list will fail when you do not configure 'public_endpoint', 'admin_endpoint' and tls-proxy (stud) is enabled - 

$ cinder --debug list
DEBUG:keystoneclient.session:REQ: curl -g -i -X GET https://10.69.4.179:5000/v2.0 -H "Accept: application/json" -H "User-Agent: python-keystoneclient"
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
DEBUG:keystoneclient.session:RESP: [200] content-length: 337 vary: X-Auth-Token keep-alive: timeout=5, max=100 server: Apache/2.4.7 (Ubuntu) connection: Keep-Alive date: Tue, 11 Aug 2015 12:19:02 GMT content-type: application/json x-openstack-request-id: req-fec04d8b-6ac0-4679-8606-67c12fadf892
RESP BODY: {"version": {"status": "stable", "updated": "2014-04-17T00:00:00Z", "media-types": [{"base": "application/json", "type": "application/vnd.openstack.identity-v2.0+json"}], "id": "v2.0", "links": [{"href": "http://10.69.4.179:5000/v2.0/", "rel": "self"}, {"href": "http://docs.openstack.org/", "type": "text/html", "rel": "describedby"}]}}

DEBUG:keystoneclient.auth.identity.v2:Making authentication request to http://10.69.4.179:5000/v2.0/tokens
ERROR: Unable to establish connection to http://10.69.4.179:5000/v2.0/tokens
$

Patch-set: 1