Force bashate to use python2.7
tox defaults to whatever version of python tox itself was run under.

bashate fails when run under python3, so force the bashate testenv to
use python2.7, regardless of the tox default.

For posterity, the py3 failure is:
[...]
File ".../devstack/.tox/bashate/lib/python3.5/site-packages/bashate/bashate.py", line 279, in check_files
    check_syntax(fname, report)
File ".../devstack/.tox/bashate/lib/python3.5/site-packages/bashate/bashate.py", line 179, in check_syntax
    for line in outputs[1].split('\n'):
TypeError: a bytes-like object is required, not 'str'

Change-Id: Ic91b5ce8cb85e376573f9bf3659d2a86cc437179