Update patch set 1
Patch Set 1:

I have looked in the logs produced by Jenkins.
Test cases fails due to file permission issues.
IOError: [Errno 13] Permission denied: '/opt/stack/new/data/tempest/tempest-availability_zone'

This error message show that my correction is active, the data directory in in right place ${DEST}/data. Without patch the data dir was in /opt/stack/data.

I have not find information in the logs that explain why we see this. In my test environment (Ubuntu on Virtualbox) I see no file permissions problem.
And same tempest test cases are sucessfull in my local environment.

-rw-rw-r-- 1 xrsjolu xrsjolu 0 nov 13 12:48 /opt/stack/new/data/tempest/tempest-availability_zone

nosetests -v api/compute/admin/  &>/home/xrsjolu/test.log

cat test.log
..
..
tempest.api.compute.admin.test_aggregates.AggregatesAdminTestJSON.test_aggregate_add_host_create_server_with_az[gate] ... ok
..
...

The changes in the devstack installtion scripts just make sure that DEST and DATA variables are handled correct and should not give these type of problem, but I must miss something ?!.
Anyone please help, I am stucked.

Patch-set: 1
Label: Code-Review=0