Prepare guestfs-support for openSUSE
With libguestfs usage for file injection now being enabled by
default as part of I568c56dbcb62ec541661364c142eff2397e3eed7
the opensuse job started to fail due to lack of guestfs images
being available.

The error in question was
NovaException: libguestfs installed but not usable (cannot
find any suitable libguestfs supermin, fixed or old-style
appliance on LIBGUESTFS_PATH (search path: /usr/lib64/guestfs)

This part is being fixed by updating package dependencies.

Unfortunately the libguestfs version in opensuse 42.2 is broken
in multiple ways (ref  https://bugzilla.suse.com/show_bug.cgi?id=1046225
and https://bugzilla.suse.com/show_bug.cgi?id=1048620 ) so we
need to temporarily disable it for suse platforms (all supported
opensuse versions share the same libguestfs package). A
followup patchset will reintroduce it asap.

Change-Id: Ie76ac0a51c1ee2ad6559917825dee1c7a91a3a76