Update patch set 1
Patch Set 1:

Xenial job passed the get-pip error but facing other error

ERROR: No matching distribution found for oslo.concurrency===4.4.0 (from -c https://releases.openstack.org/constraints/upper/master (line 24))

I think we need to handle 3.5 req also. hummmm

Patch-set: 1
Work-in-progress: false