Update patch set 16
Patch Set 16:

e832cfd7248ba453300abcc6a0eca555ed478008 that last changed libvirt-python to 5.1.0 is from Tue Mar 5 06:14:31 2019 +0000 .


Leap 15.2 shipped with a version of libvirt https://build.opensuse.org/package/show/openSUSE:Leap:15.2/libvirt that was last changed 2020-06-10 14:49 UTC. It was updated twice https://build.opensuse.org/package/show/openSUSE:Leap:15.2:Update/libvirt.13730 on 2020-09-19 12:20 UTC and https://build.opensuse.org/package/show/openSUSE:Leap:15.2:Update/libvirt.14632 on 2020-10-30 17:23 UTC.


I tested building the package of python-libvirt 5.1.0 available in Leap 15.1 with all 3 versions of libvirt mentioned above. All failed in the same way as this log:


  /usr/bin/python generator.py libvirt /usr/share/libvirt/api/libvirt-api.xml
    Found 466 functions in /usr/share/libvirt/api/libvirt-api.xml
    Found 0 functions in libvirt-override-api.xml
    Generated 370 wrapper functions
    Missing type converters:
    virTypedParameterPtr *:1
    virNetworkPortPtr **:1
    virTypedParameterPtr:1
    virNetworkPortPtr:12
    ERROR: failed virConnectSetIdentity
    ERROR: failed virDomainGetGuestInfo
    ERROR: failed virNetworkListAllPorts
    ERROR: failed virNetworkPortCreateXML
    ERROR: failed virNetworkPortDelete
    ERROR: failed virNetworkPortFree
    ERROR: failed virNetworkPortGetNetwork
    ERROR: failed virNetworkPortGetParameters
    ERROR: failed virNetworkPortGetUUID
    ERROR: failed virNetworkPortGetUUIDString
    ERROR: failed virNetworkPortGetXMLDesc
    ERROR: failed virNetworkPortLookupByUUID
    ERROR: failed virNetworkPortLookupByUUIDString
    ERROR: failed virNetworkPortRef
    ERROR: failed virNetworkPortSetParameters


That should have covered the version that was working before, but seems not. What made it work before?

Patch-set: 16