lib/tempest: Specify python3 version in image_size_in_gib
the function in lib/tempest called image_size_in_gib
does the following:

   echo $size | python -c "import math; import six; ..."

in systems where python2 is installed and package six is only
part of python3, the following error will occur:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
  ImportError: No module named six

So, explicitly use ${PYTHON3_VERSION}, since python
may mean python2.

Change-Id: Ibc93f191bb83249de8c1d7ef430447b5d54aa736