Update patch set 9
Patch Set 9:

though, looks like swiftclient needs to be fixed:

http://logs.openstack.org/30/312230/9/check/gate-swift-dsvm-functional-ubuntu-xenial-nv/efe229f/console.html#_2017-02-22_16_52_53_357586

swiftclient.exceptions.ClientException: Authorization Failure. Authorization failed: Not Found (HTTP 404)

Patch-set: 9