Update patch set 4
Patch Set 4:

The error I saw in devstack was the following:

Installing collected packages: lxml, paramiko, taskflow, rtslib-fb, cinder, ecd\
sa, alembic, networkx, futures, Mako
  Running setup.py install for lxml
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distributi\
on option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.2.5.
    Building without Cython.
    ERROR: /bin/sh: xslt-config: command not found

    ** make sure the development packages of libxml2 and libxslt are installed \
**

It looks like lxml requires xslt-config which is provided by libxstl-devel

Talking to fpercoco it seems like this is an issue with copying things from oslo-incubator and not oslo-rootwrap.  He mentioned the following commit as a possible source of the issue:
https://github.com/openstack-dev/devstack/commit/0718568b1203bd11058d3cd28402f84841c01dda

I noticed that the xslt-config error happens much earlier in the devstack process (I see it in keystone section for starters) but keystone doesn't cause the entire devstack script to fail, it just keeps going with the errors present.

Patch-set: 4
Reviewer: Gerrit User 8584 <8584@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Code-Review=0