Make PyYAML overridable on Red Hat family distros
This patch fixes an early stack issue where the following error message
would be presented:

ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project
and thus we cannot accurately determine which files belong to it which
would lead to only a partial uninstall.

Change-Id: I2876ee58ab6b73682869d6b4e684e10ac5e56ad9