[stable-only] Preinstall pbr for devstack-tools and unblock gate
This patch contains multiple fixes to unblock gate.

Due to "Deprecation of non-SNI compatible clients" [1], when
devstack-tools is installed in early phase (in neutron-grenade job for
example) and pbr is not yet installed, the pip command fails with the
following error in xenial based environments:

File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 657, in easy_install
  raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pbr>=1.8')

This is because setuptools' easy_install is used, which is non-SNI
compatible in xenial base image (and python 3.5). With this patch the
issue can be avoided by preinstalling pbr just before the installation
of devstack-tools.

NOTE(elod.illes): neutron-grenade is still part of the gate for
multiple projects in stable/queens (nova, neutron, cinder, keystone),
so set it back to voting in devstack, too.

Patch I01408f2f2959b0788fe712ac268a526502226ee9 also needed to be
squashed into this patch, to fix the gate:

Pin nodeset as xenial for devstack unit test job

devstack-unit-tests job running on devstack stable/rocky
branch had no nodeset and use default one which is now xenial.

This commit explicitly pin the xenial nodeset on stable/rocky.
(cherry picked from commit 77561e7e172daf9401b66ab4d076e7311acd24ed)

NOTE(elod.illes): since cinder project's stable/pike branches are in
End-of-Life state and they do not exist anymore, we have to use
pike-eol tag instead for those repositories.

[1] https://github.com/pypa/pypi-support/issues/978

Change-Id: I0edd4734df8ac7976d3090b75ca4c033b8ff0f2c
(cherry picked from commit 052d7f24423e34136db94f6e40e31cf1c0697be5)
(cherry picked from commit 1b9ca1751adf8460236e6a123e448cb54dd03e62)