Update patch set 1
Patch Set 1: No score

Hmm, well I re-ran my tests after adding --allow_resize_on_same_host to my Diablo stack.sh and still get these errors:

======================================================================
ERROR: The server's RAM and disk space should be modified to that of
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpipes/repos/tempest/tempest/tests/test_server_actions.py", line 97, in test_resize_server_confirm
    self.client.wait_for_server_status(self.server_id, 'VERIFY_RESIZE')
  File "/home/jpipes/repos/tempest/tempest/services/nova/json/servers_client.py", line 147, in wait_for_server_status
    raise exceptions.BuildErrorException(server_id=server_id)
BuildErrorException: Server 14 failed to build and is in ERROR status

======================================================================
ERROR: The server's RAM and disk space should return to its original
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jpipes/repos/tempest/tempest/tests/test_server_actions.py", line 115, in test_resize_server_revert
    self.client.wait_for_server_status(self.server_id, 'VERIFY_RESIZE')
  File "/home/jpipes/repos/tempest/tempest/services/nova/json/servers_client.py", line 147, in wait_for_server_status
    raise exceptions.BuildErrorException(server_id=server_id)
BuildErrorException: Server 15 failed to build and is in ERROR status

Is this flag something that was added in Essex?

Patch-set: 1
Reviewer: Gerrit User 7 <7@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Code-Review=0