Install guestfs-support for openSUSE
With libguestfs usage for file injection now being enabled by
default as part of I568c56dbcb62ec541661364c142eff2397e3eed7
the opensuse job started to fail due to lack of guestfs images
being available.

The error in question was
NovaException: libguestfs installed but not usable (cannot
find any suitable libguestfs supermin, fixed or old-style
appliance on LIBGUESTFS_PATH (search path: /usr/lib64/guestfs)

In addition the suse deployment requires a temporary workaround
until guestfs support has been fixed in the distribution.

Change-Id: Ie76ac0a51c1ee2ad6559917825dee1c7a91a3a76