Update patch set 8
Patch Set 8:

thanks.

seems few more place we need to adjust the creds.

https://zuul.opendev.org/t/openstack/build/83ef9dd762614b99b8f9715c80c82971

++ lib/neutron_plugins/services/l3:create_neutron_initial_network:185 :   oscwrap --os-cloud devstack-system-admin --os-region RegionOne subnet pool create shared-default-subnetpool-v4 --project 3ab3976efc4e417a941045a0587cb3ab --default-prefix-length 26 --pool-prefix 10.1.0.0/20 --share --default -f value -c id
HttpException: 403: Client Error for url: https://10.210.192.232:9696/v2.0/subnetpools, ((rule:create_subnetpool and rule:create_subnetpool:is_default) and rule:create_subnetpool:shared) is disallowed by policy

Patch-set: 8
Reviewer: Gerrit User 8556 <8556@4a232e18-c5a9-48ee-94c0-e04e7cca6543>