Revert "Do not download Fedora cloud image for heat"
The image also used by sahara, changing the condition to
test sahara availability, otherwise devstack fails with:

 ++ openstack --os-url http://<myhost>:9292 image set
Fedora-x86_64-20-20140618-sda --property _sahara_tag_0.1=True --property
_sahara_tag_fake=True --property _sahara_username=fedora
ERROR: openstack No image with a name or ID of
'Fedora-x86_64-20-20140618-sda' exists.

This reverts commit 89983b6dfe15e8e83f390e9870cc3ddfbf2b8243.

Change-Id: Ibc96d8d11bc489536825b445a809eabbba4b7813