Update patch set 1
Patch Set 1:

Why this? I'm getting strange errors low in the python stack with python 3 in sahara:

Sep 06 10:24:23.191293 ubuntu-xenial-limestone-regionone-0001818021 sahara-engine[17273]: 2018-09-06 10:24:23.162 17399 ERROR oslo_db.sqlalchemy.exc_filters [req-6bf478b8-25c8-419e-a8d8-c6090f046422 302eae71ad5e4ae68edc3599f38fdd4c c7f71c14c2f94647ba692ee9789240e0 - - -] [instance: none, cluster: bf1bd13b-dbf5-4d45-b83f-2e6d7dcf2499] DB exception wrapped.: AttributeError: 'list' object has no attribute 'lower'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 127, in _escape_args
    return dict((key, conn.literal(val)) for (key, val) in args.items())
  File "/usr/local/lib/python3.5/dist-packages/pymysql/cursors.py", line 127, in <genexpr>
    return dict((key, conn.literal(val)) for (key, val) in args.items())
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 469, in literal
    return self.escape(obj, self.encoders)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 456, in escape
    return "'" + self.escape_string(obj) + "'"
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 475, in escape_string
    return converters.escape_string(s)
  File "/usr/local/lib/python3.5/dist-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
  File "/usr/local/lib/python3.5/dist-packages/oslo_i18n/_message.py", line 85, in translate
    self.has_plural_form)
  File "/usr/local/lib/python3.5/dist-packages/oslo_i18n/_message.py", line 117, in _translate_msgid
    fallback=True)
  File "/usr/lib/python3.5/gettext.py", line 428, in translation
    mofiles = find(domain, localedir, languages, all=True)
  File "/usr/lib/python3.5/gettext.py", line 385, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib/python3.5/gettext.py", line 114, in _expand_lang
    loc = locale.normalize(loc)
  File "/usr/lib/python3.5/locale.py", line 392, in normalize
    code = localename.lower()
AttributeError: 'list' object has no attribute 'lower'


I suspect that the root cause could be a unproperly configured locale, so let's try to use the canonical name here. Maybe it's a different issue, but it's worth trying.

Patch-set: 1