Update patch set 3
Patch Set 3:

Same problem with patch 3 :-(
Patch works for me but not for Jenkins.

Console log show:
2013-11-21 10:13:14.026 | 2013-11-21 10:13:13 ++ mkdir -p /opt/stack/new/data/tempest
2013-11-21 10:13:14.027 | 2013-11-21 10:13:13 ++ chmod 755 /opt/stack/new/data/tempest

But Jenkins fails due to:
OError: [Errno 13] Permission denied: '/opt/stack/new/data/tempest/tempest-availability_zone'

I do not know how to proceed with this now.

Patch-set: 3
Reviewer: Gerrit User 9267 <9267@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Code-Review=0