Update patch set 20
Patch Set 20:

Nothing provides package debootstrap. This is required to build DIB-built Ubuntu-based images.



Package iptables-1.8.2-9.el8_0.1.x86_64 is already installed.                                                                                                                            
Package iputils-20180629-1.el8.x86_64 is already installed.        
Package sqlite-3.26.0-3.el8.x86_64 is already installed.                                                                                                                                  
Package sudo-1.8.25p1-4.el8.x86_64 is already installed.                                                                                                                                  
Package ipset-6.38-3.el8.x86_64 is already installed.                                                                                                                                    
Package conntrack-tools-1.4.4-9.el8.x86_64 is already installed.                                                                                                                          
Package keepalived-2.0.10-4.el8_0.2.x86_64 is already installed.
No match for argument: debootstrap                              
Package rsyslog-8.37.0-9.el8.x86_64 is already installed.
Error: Unable to find a match                               
++functions-common:yum_install:1404         echo YUM_FAILED 1
YUM_FAILED 1                                          
++functions-common:yum_install:1405         result=1         
++functions-common:yum_install:1407         time_stop yum_install
++functions-common:time_stop:2336           local name
++functions-common:time_stop:2337           local end_time
++functions-common:time_stop:2338           local elapsed_time
++functions-common:time_stop:2339           local total
++functions-common:time_stop:2340           local start_time
++functions-common:time_stop:2342           name=yum_install
++functions-common:time_stop:2343           start_time=1576056056397
++functions-common:time_stop:2345           [[ -z 1576056056397 ]]
+++functions-common:time_stop:2348           date +%s%3N
++functions-common:time_stop:2348           end_time=1576056056987
++functions-common:time_stop:2349           elapsed_time=590
++functions-common:time_stop:2350           total=10723
++functions-common:time_stop:2352           _TIME_START[$name]=
++functions-common:time_stop:2353           _TIME_TOTAL[$name]=11313
++functions-common:yum_install:1416         '[' 1 == 2 ']'
++functions-common:yum_install:1420         return 1
+functions-common:real_install_package:1   exit_trap

Patch-set: 20