Update patch set 8
Patch Set 8:

This change apparently broke clean "./redstack install". Existing installation do not suffer the issue.

WARNING: urllib3.connectionpool HttpConnectionPool is full, discarding connection: 192.168.204.132
ERROR: openstack <html>
 <head>
  <title>500 Internal Server Error</title>
 </head>
 <body>
  <h1>500 Internal Server Error</h1>
  Failed to upload image e316960f-a4a6-4422-9cba-bf5b2a66c5cf<br /><br />

 </body>
</html> (HTTP 500)
+ ramdisk_id=
+ openstack --os-token 9640b24da46b4426893e28069c1362ac --os-url http://192.168.204.132:9292 image create cirros-0.3.2-x86_64-uec --public --container-format ami --disk-format ami
WARNING: urllib3.connectionpool HttpConnectionPool is full, discarding connection: 192.168.204.132
ERROR: openstack <html>
 <head>
  <title>500 Internal Server Error</title>
 </head>
 <body>
  <h1>500 Internal Server Error</h1>
  Failed to upload image 81f6f4eb-c4b6-48db-bb1c-3dcd5330333e<br /><br />

 </body>
</html> (HTTP 500)
+ exit_trap
+ local r=1
++ jobs -p
+ jobs=
+ [[ -n '' ]]
+ kill_spinner
+ '[' '!' -z '' ']'
+ [[ 1 -ne 0 ]]
+ echo 'Error on exit'
Error on exit
+ [[ -z '' ]]
+ /home/petmal/devstack/tools/worlddump.py
World dumping... see ./worlddump-2015-01-27-152755.txt for details
+ exit 1

Patch-set: 8
Reviewer: Gerrit User 14576 <14576@4a232e18-c5a9-48ee-94c0-e04e7cca6543>
Label: Verified=0